- index.js
> backend setup complete

- index.js
banner, productFeature, teamDetails api set
> banner, productFeature, teamDetails api set

- index.js
- vercel.json
> review post and get api added

- index.js
> articles api added

- index.js
> user details post api added

- index.js
> user get api added

- index.js
> admin and visitor role get

- index.js
> get user api added

- index.js
> get articles by id added

- index.js
> user role set api added

- index.js
> 3 user role added

- index.js
> update user data added

- index.js
> new articles api added

- index.js
> all articles added

- index.js
> articles api updated

- index.js
> added favorite location btn

- index.js
> articles added

- index.js
> get favorite location by email

- index.js
> favLocation api updated

- index.js
> added favorite location

- index.js
- package.json
> payment system

- index.js
> First testing commit from Nizam

- index.js
> bug fixing

- index.js
> user pagination
